module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  purge: [
    './resources/**/*.blade.php',
    './resources/**/*.less',
    './resources/**/*.js',
    './resources/**/*.vue'
  ],
  theme: {
    backgroundColor: (theme) => theme('colors'),
    borderColor: (theme) => ({
      ...theme('colors'),
      default: theme('colors.gray.300', 'currentColor'),
    }),
    fontFamily: {
      sans: [
        'Roboto',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        '"Segoe UI"',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        '"Fira Sans"',
        '"Droid Sans"',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'Constantia',
        '"Lucida Bright"',
        'Lucidabright',
        '"Lucida Serif"',
        'Lucida',
        '"DejaVu Serif"',
        '"Bitstream Vera Serif"',
        '"Liberation Serif"',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'Georgia',
        'serif',
      ],
      mono: ['Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    height: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    inset: { 0: '0', auto: 'auto' },
    letterSpacing: { normal: '0' },
    maxHeight: { full: '100%', screen: '100vh' },
    maxWidth: {
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
    },
    minHeight: ['0'],
    minWidth: ['0'],
    textColor: (theme) => theme('colors'),
    width: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      full: '100%',
      screen: '100vw',
    }),
    extend: {
      colors: {
        black: '#22292f',
        'grey-darkest': '#3d4852',
        'grey-darker': '#606f7b',
        'grey-dark': '#8795a1',
        grey: '#7e8b95',
        'grey-light': '#dae1e7',
        'grey-lighter': '#e4eaed',
        'grey-lightest': '#f7f7f7',
        white: '#ffffff',
        'red-darkest': '#3b0d0c',
        'red-darker': '#621b18',
        'red-dark': '#cc1f1a',
        red: '#e3342f',
        'red-light': '#ef5753',
        'red-lighter': '#f9acaa',
        'red-lightest': '#fcebea',
        'orange-darkest': '#462a16',
        'orange-darker': '#613b1f',
        'orange-dark': '#de751f',
        orange: '#f6993f',
        'orange-light': '#faad63',
        'orange-lighter': '#fcd9b6',
        'orange-lightest': '#fff5eb',
        'yellow-darkest': '#453411',
        'yellow-darker': '#684f1d',
        'yellow-dark': '#f2d024',
        yellow: '#ffed4a',
        'yellow-light': '#fff382',
        'yellow-lighter': '#fff9c2',
        'yellow-lightest': '#fcfbeb',
        'green-darkest': '#0f2f21',
        'green-darker': '#1a4731',
        'green-dark': '#1f9d55',
        green: '#38c172',
        'green-light': '#51d88a',
        'green-lighter': '#a2f5bf',
        'green-lightest': '#e3fcec',
        'teal-darkest': '#0d3331',
        'teal-darker': '#20504f',
        'teal-dark': '#38a89d',
        teal: '#4dc0b5',
        'teal-light': '#64d5ca',
        'teal-lighter': '#a0f0ed',
        'teal-lightest': '#e8fffe',
        'blue-darkest': '#203950',
        'blue-darker': '#28556e',
        'blue-dark': '#2779bd',
        blue: '#229be1',
        'blue-light': '#6cb2eb',
        'blue-lighter': '#bcdefa',
        'blue-lightest': '#eff8ff',
        'indigo-darkest': '#191e38',
        'indigo-darker': '#2f365f',
        'indigo-dark': '#5661b3',
        indigo: '#6574cd',
        'indigo-light': '#7886d7',
        'indigo-lighter': '#b2b7ff',
        'indigo-lightest': '#e6e8ff',
        'purple-darkest': '#21183c',
        'purple-darker': '#382b5f',
        'purple-dark': '#794acf',
        purple: '#9561e2',
        'purple-light': '#a779e9',
        'purple-lighter': '#d6bbfc',
        'purple-lightest': '#f3ebff',
        'pink-darkest': '#451225',
        'pink-darker': '#6f213f',
        'pink-dark': '#eb5286',
        pink: '#f66d9b',
        'pink-light': '#fa7ea8',
        'pink-lighter': '#ffbbca',
        'pink-lightest': '#ffebef',
      },
    },
  },
  variants: {
      extend: {
          fontWeight: ['hover', 'focus'] 
      } 
  },
}
